# Ethereum Cryptocurrency Tables
- balances
- blocks
- contracts
- logs
- token_transfers
- tokens
- traces
- transactions

In [19]:
import numpy as np
import pandas as pd
import os
from bs4 import BeautifulSoup as bs
from google.cloud import bigquery
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
pd.set_option('display.max_rows', 2000)

# 1. Token Transfer

In [6]:
token_transfer = pd.read_csv("/Users/rparama/Downloads/Dataset/token_transfers_2019.csv")

In [7]:
token_transfer.head()

token_address  \
0  0x085b0fdf115aa9e16ae1bddd396ce1f993c52220   
1  0x085b0fdf115aa9e16ae1bddd396ce1f993c52220   
2  0xde6fb6a5adbe6415cdaf143f8d90eb01883e42ac   
3  0xde6fb6a5adbe6415cdaf143f8d90eb01883e42ac   
4  0x80dafcf47a0199b71c187c84ba68cfb999f2a1ef   

                                 from_address  \
0  0x2e4c7acc76c124c470172678c2f6a63c2192fdcb   
1  0x2e4c7acc76c124c470172678c2f6a63c2192fdcb   
2  0x39a9057d8f1c69680f35d2c1357b5132876416db   
3  0x39a9057d8f1c69680f35d2c1357b5132876416db   
4  0x39a9057d8f1c69680f35d2c1357b5132876416db   

                                   to_address                 value  \
0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  61000000000000000000   
1  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a    533513770881623000   
2  0x501f0e393f1baaf5bfcc9c6bacf575c9ccb89644  14660000000000000000   
3  0x501f0e393f1baaf5bfcc9c6bacf575c9ccb89644  10000000000000000000   
4  0x8fb97ab5ddedccc2e4acdf4894a341ce4e8eb058    500000000000000000   

                                    transaction_hash  log_index  \
0  0x08c83d1aadc1765c1624be22399802f3373975497d89...          6   
1  0xb6a44062f6ab06a12b6a0b197b395547aa96fce54b02...          9   
2  0x79cad67e831ba1a9af12d52eb5736f505b315be62543...          1   
3  0x4cc717a0e7c7ac8a4c9b270ed22c787cc791c11f3f33...          1   
4  0xef404b13a93cd4568f0d7b060c7eaffec22df52c1ab3...          2   

             block_timestamp  block_number  \
0  2019-05-12 03:40:03+00:00       8018159   
1  2019-05-12 03:57:49+00:00       8018241   
2  2019-05-12 21:12:33+00:00       8022696   
3  2019-05-12 21:28:43+00:00       8022763   
4  2019-05-12 16:52:36+00:00       8021539   

                                          block_hash  
0  0xfb39b76b04d7f8d5c77528a559cfc0fa7f63d99b3b7e...  
1  0x1c272b9179f2328d1d29554fa1443e444ee5463c22d9...  
2  0x112d497b5da1fd4c1067a9228ad29cbfe831a0ba890e...  
3  0xd50b2b214ca21e94b7d45c6d0ea582e9962e50e13f8b...  
4  0x96113a87534c6d03966e9da7cd31ef7853576d4819f8...

In [8]:
token_transfer["token_address"].count(), token_transfer["token_address"].nunique()

(224175, 180)

# 2. Trace

In [9]:
trace = pd.read_csv("/Users/rparama/Downloads/Dataset/traces_2019.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning:

Columns (4,8,9,13,14) have mixed types.Specify dtype option on import or set low_memory=False.



In [12]:
trace.shape

(69415366, 20)

In [13]:
trace.head()

transaction_hash  transaction_index  \
0  0xf8e255d631bfbd9971fc42b38bf61a472314d417858d...               36.0   
1  0xca002523f0291629ede8e9874bc8f3987390b935f676...               31.0   
2  0x8509b195ec12f4f9c284038b2d2e24caa5ab889dbe8b...               32.0   
3  0xca002523f0291629ede8e9874bc8f3987390b935f676...               31.0   
4  0xca002523f0291629ede8e9874bc8f3987390b935f676...               31.0   

                                 from_address  \
0  0x0000000000b3f879cb30fe243b4dfee438691c04   
1  0x0000000000b3f879cb30fe243b4dfee438691c04   
2  0x0000000000b3f879cb30fe243b4dfee438691c04   
3  0x0000000000b3f879cb30fe243b4dfee438691c04   
4  0x0000000000b3f879cb30fe243b4dfee438691c04   

                                   to_address value  \
0  0x6157943e7f165884f47c3341bb4a805d7fc62a4e     0   
1  0xe444538230669c941d86f9f3ffc9d401fbd1f788     0   
2  0x3ed97771552bd6041f4aa657f79c890c3189ed26     0   
3  0x9230ea2a3c7da5bb9aadc676a1e2e4a5692c4109     0   
4  0x1341829acc4aff17d5507c66bf501da3b2d0d82f     0   

                                               input  \
0  0x756eb3f879cb30fe243b4dfee438691c043318585733...   
1  0x756eb3f879cb30fe243b4dfee438691c043318585733...   
2  0x756eb3f879cb30fe243b4dfee438691c043318585733...   
3  0x756eb3f879cb30fe243b4dfee438691c043318585733...   
4  0x756eb3f879cb30fe243b4dfee438691c043318585733...   

                                           output trace_type call_type  \
0  0x6eb3f879cb30fe243b4dfee438691c043318585733ff     create       NaN   
1  0x6eb3f879cb30fe243b4dfee438691c043318585733ff     create       NaN   
2  0x6eb3f879cb30fe243b4dfee438691c043318585733ff     create       NaN   
3  0x6eb3f879cb30fe243b4dfee438691c043318585733ff     create       NaN   
4  0x6eb3f879cb30fe243b4dfee438691c043318585733ff     create       NaN   

  reward_type       gas  gas_used  subtraces trace_address error  status  \
0         NaN  139191.0    4418.0          0            22   NaN       1   
1         NaN  535241.0    4418.0          0            11   NaN       1   
2         NaN  535241.0    4418.0          0            11   NaN       1   
3         NaN  427227.0    4418.0          0            14   NaN       1   
4         NaN  823277.0    4418.0          0             3   NaN       1   

             block_timestamp  block_number  \
0  2019-11-20 14:39:11+00:00       9227204   
1  2019-11-20 14:39:11+00:00       9227204   
2  2019-11-20 14:39:11+00:00       9227204   
3  2019-11-20 14:39:11+00:00       9227204   
4  2019-11-20 14:39:11+00:00       9227204   

                                          block_hash  trace_id  
0  0xe47ba6f0ed418e4c3d5d6a2f23fe8b2eb01a6662a4e4...       NaN  
1  0xe47ba6f0ed418e4c3d5d6a2f23fe8b2eb01a6662a4e4...       NaN  
2  0xe47ba6f0ed418e4c3d5d6a2f23fe8b2eb01a6662a4e4...       NaN  
3  0xe47ba6f0ed418e4c3d5d6a2f23fe8b2eb01a6662a4e4...       NaN  
4  0xe47ba6f0ed418e4c3d5d6a2f23fe8b2eb01a6662a4e4...       NaN

In [84]:

dfETH = pd.merge(trace,token_transfer, how = 'inner', left_on=['transaction_hash'],right_on=['transaction_hash'])
dfETH.head(10)


transaction_hash  transaction_index  \
0  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0   
1  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0   
2  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0   
3  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0   
4  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0   
5  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0   
6  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0   
7  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0   
8  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0   
9  0x12d11793515571efff5f876397e714aa4d1cf3b82749...                7.0   

                               from_address_x  \
0  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a   
1  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a   
2  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a   
3  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a   
4  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a   
5  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a   
6  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a   
7  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a   
8  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a   
9  0x94f9e355fe66eeb5bf8b09fbdf493e1f64680f2a   

                                 to_address_x              value_x  \
0  0x51a5c4d6b39b4f789464a9a8e434447764953f92  3600000000000000000   
1  0x51a5c4d6b39b4f789464a9a8e434447764953f92  3600000000000000000   
2  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0   
3  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0   
4  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0   
5  0xac55641cbb734bdf6510d1bbd62e240c2409040f                    0   
6  0x92eeb915dafe3803f8a9d12000765c3b6af6d5fd     9022556390977443   
7  0x92eeb915dafe3803f8a9d12000765c3b6af6d5fd     9022556390977443   
8  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443   
9  0x3ec00ee8a4fbe81e7eea328029ce490654e8e11a  3609022556390977443   

                                               input  \
0                                                 0x   
1                                                 0x   
2  0xa9059cbb00000000000000000000000094f9e355fe66...   
3  0xa9059cbb00000000000000000000000094f9e355fe66...   
4  0xa9059cbb00000000000000000000000094f9e355fe66...   
5  0xa9059cbb00000000000000000000000094f9e355fe66...   
6                                                 0x   
7                                                 0x   
8  0xa4ff9c34000000000000000000000000000000000000...   
9  0xa4ff9c34000000000000000000000000000000000000...   

                                              output trace_type call_type  \
0                                                 0x       call      call   
1                                                 0x       call      call   
2  0x00000000000000000000000000000000000000000000...       call      call   
3  0x00000000000000000000000000000000000000000000...       call      call   
4  0x00000000000000000000000000000000000000000000...       call      call   
5  0x00000000000000000000000000000000000000000000...       call      call   
6                                                 0x       call      call   
7                                                 0x       call      call   
8                                                 0x       call      call   
9                                                 0x       call      call   

  reward_type  ...                                       block_hash_x  \
0         NaN  ...  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...   
1         NaN  ...  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...   
2         NaN  ...  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...   
3         NaN  ...  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...   
4         NaN  ...  0x03094a5a677790ae0dd74fabcd3c309f5379f804cc4a...

In [15]:
dfETH.shape

(1600145, 28)

In [16]:
dfETH["token_address"].count(), dfETH["token_address"].nunique()

(1600145, 161)

In [33]:
# File metadata/Schema analysis


print("| Column Name","Record Count","Unique Count","Null Count","Total Count")
for col in dfETH.columns:
    print(([col.ljust(15),dfETH[col].count(),dfETH[col].nunique(),
                            dfETH[col].isnull().sum(),dfETH[col].count()+dfETH[col].isnull().sum()]))


| Column Name Record Count Unique Count Null Count Total Count
['transaction_hash', 1600145, 156411, 0, 1600145]
['transaction_index', 1600145, 206, 0, 1600145]
['from_address_x ', 1600145, 2883, 0, 1600145]
['to_address_x   ', 1600145, 2650, 0, 1600145]
['value_x        ', 1600145, 20842, 0, 1600145]
['input          ', 1600145, 219620, 0, 1600145]
['output         ', 1600101, 4940, 44, 1600145]
['trace_type     ', 1600145, 2, 0, 1600145]
['call_type      ', 1598414, 2, 1731, 1600145]
['reward_type    ', 0, 0, 1600145, 1600145]
['gas            ', 1600145, 84721, 0, 1600145]
['gas_used       ', 1600101, 11808, 44, 1600145]
['subtraces      ', 1600145, 34, 0, 1600145]
['trace_address  ', 1382469, 406, 217676, 1600145]
['error          ', 44, 1, 1600101, 1600145]
['status         ', 1600145, 2, 0, 1600145]
['block_timestamp_x', 1600145, 69483, 0, 1600145]
['block_number_x ', 1600145, 69483, 0, 1600145]
['block_hash_x   ', 1600145, 69483, 0, 1600145]
['trace_id       ', 0, 0, 1600145, 16

In [85]:

dfETH = dfETH[(dfETH["trace_type"] == 'call') &
              (dfETH["status"] == 1) & 
              (dfETH["call_type"] == 'call')].reset_index().drop('index',axis=1)


In [76]:
dfETH.trace_type.unique()

array(['call'], dtype=object)

In [77]:
dfETH.call_type.unique()

array(['call'], dtype=object)

In [78]:
dfETH.reward_type.unique()

array([nan], dtype=object)

In [79]:
dfETH.error.unique()

array([nan], dtype=object)

In [80]:
dfETH.status.unique()

array([1])

In [81]:
dfETH.trace_id.unique()

array([nan])

In [86]:

dfETH.drop(['trace_type','call_type','reward_type','error','status','trace_id','trace_address'], axis=1, inplace=True)


In [87]:
print("| Column Name","Record Count","Unique Count","Null Count","Total Count")
for col in dfETH.columns:
    print(([col.ljust(15),dfETH[col].count(),dfETH[col].nunique(),
                            dfETH[col].isnull().sum(),dfETH[col].count()+dfETH[col].isnull().sum()]))

| Column Name Record Count Unique Count Null Count Total Count
['transaction_hash', 1598326, 156381, 0, 1598326]
['transaction_index', 1598326, 206, 0, 1598326]
['from_address_x ', 1598326, 2880, 0, 1598326]
['to_address_x   ', 1598326, 935, 0, 1598326]
['value_x        ', 1598326, 20842, 0, 1598326]
['input          ', 1598326, 219587, 0, 1598326]
['output         ', 1598326, 4909, 0, 1598326]
['gas            ', 1598326, 84592, 0, 1598326]
['gas_used       ', 1598326, 11780, 0, 1598326]
['subtraces      ', 1598326, 34, 0, 1598326]
['block_timestamp_x', 1598326, 69457, 0, 1598326]
['block_number_x ', 1598326, 69457, 0, 1598326]
['block_hash_x   ', 1598326, 69457, 0, 1598326]
['token_address  ', 1598326, 148, 0, 1598326]
['from_address_y ', 1598326, 2566, 0, 1598326]
['to_address_y   ', 1598326, 28948, 0, 1598326]
['value_y        ', 1598326, 32150, 0, 1598326]
['log_index      ', 1598326, 353, 0, 1598326]
['block_timestamp_y', 1598326, 69457, 0, 1598326]
['block_number_y ', 1598326, 6

In [88]:
dfETH.to_csv('/Users/rparama/Downloads/Dataset/1_ETH_DataPrepration.csv',index=False)